Modified PlaceNameLayer to work around a change in Java 7's implementation of CharBuffer.subSequence that results in a NoSuchMethodError when run on Java 6.